# Generated by Django 5.0.3 on 2024-03-27 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='owner',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
            preserve_default=False,
        ),
    ]
