# Generated by Django 5.0.3 on 2024-04-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_book_id_alter_book_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='owner_address',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books-mages/'),
        ),
    ]
